### PR TITLE
CB-11050 Removing the flaky XHR Test

### PR DESCRIPTION
**Pull request by rakatyal**
This test isn't really needed since it's just checking the browser's functionality.

### CODE REVIEW

**Comment by rakatyal** [comment]
@sarangan12 , @omefire: Please review.

**Comment by omefire** [comment]
It seems like this whole test suite is only about checking browser/webview functionality.
Do we still really need them ?

**Comment by purplecabbage** [comment]
Yes it is needed. jQuery mobile broke because apps were not permitted to xhr to their own resources. 
It IS browser functionality, BUT we still need tests to prove we are not breaking it.

**Comment by omefire** [comment]
Thanks @purplecabbage for confirming.

**Comment by omefire** [comment]
@rakatyal Is the flakiness related to the host we're XHR'ing to ? Would switching from 'http://cordova-filetransfer.jitsu.com' to something else(e.g: 'http://google.com') solve this ? If so, let's replace instead of removing the test.

Also, Please add a comment to the tests with @purplecabbage 's comment. It would clarify why these tests are needed and remind us not to think about removing them in the future.

**Comment by rakatyal** [comment]
Thanks @purplecabbage for the info. @omefire: Yes the flakiness is related to the host. It becomes randomly unavailable. I will update the PR to make get call to google.

**Comment by omefire** [comment]
LGTM!

**Comment by omefire** [comment]
Haha, I just realized we should have updated the title to 'Fixing flaky XHR Test' instead of 'Removing ...'.
Oh well, ...

**Pull request closed without merging**
