### PR TITLE
CB-8131 Rewrote non plugin auto tests for Jasmine 2.0

### PR DESCRIPTION
**Pull request by MariaBukharina**
https://issues.apache.org/jira/browse/CB-8131

### CODE REVIEW

**Comment by dblotsky** [comment]
I currently get a `Missing semicolon.` error in `src/android/exec.js` when I run createmobilespec. This may be fixed in the latest version: please merge with master.

**Comment by alsorokin** [comment]
I've rebased this. No error for me.

**Comment by dblotsky** [comment]
On OSX, everything is green. On Windows, everything except Whitelist is green. On Whitelist I'm seeing an error, `... encountered a declaration exception` for the `test()` and `match()` specs, but they still show as `pending`. Is this expected? It looks like maybe Jasmine is getting a bit confused at the deeper use of `pending()`. Do you know why this happens?

**Comment by alsorokin** [comment]
It looks like Jasmine executes pending specs anyway, it just don't mark them red if they fail.

**Comment by dblotsky** [comment]
Ah, that makes sense. Thanks!

**Comment by alsorokin** [comment]
I've played with it for some time and found that `pending()` actually throws an exception that must be handled by Jasmine and spec should terminate. In this case it didn't terminate because we threw `pending()` from `describe` and not from `it`.

**Comment by dblotsky** [comment]
Oh, ok. Nice catch. Do you think we should submit a fix?

**Pull request closed without merging**
