### PR TITLE
CB-8694 Replaced dependencies plugin with command line parameter

### PR DESCRIPTION
**Pull request by alsorokin**
https://issues.apache.org/jira/browse/CB-8694

### CODE REVIEW

**Comment by nikhilkh** [comment]
LGTM

**Comment by dblotsky** [comment]
This fails to get tests when `--plugins` is specified. Also, this is a major breaking change to any tool or person that depends on modifying the dependencies plugin.

**Comment by alsorokin** [comment]
@dblotsky Ah, it couldn't locate mobilespec tests, thanks for pointing that out!
Fixed it.

**Comment by dblotsky** [comment]
Tested on my end. LGTM.

**Pull request closed without merging**
